# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Runned at')),
                ('status', models.CharField(choices=[('success', 'Success'), ('partially', 'Partially'), ('error', 'Error')], max_length=20, verbose_name='Status')),
            ],
            options={
                'verbose_name_plural': 'Backups',
                'verbose_name': 'Backup',
            },
        ),
        migrations.CreateModel(
            name='BackupFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(verbose_name='Filename')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yadbu.Backup', verbose_name='Backup')),
            ],
            options={
                'verbose_name_plural': 'Backuped Files',
                'verbose_name': 'Backuped File',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.TextField(help_text='Full filename or mask, like `/path/to/file/my_backup.sql`, `/path/to/folder/*` or `/path/to/folder/*.jpeg`', verbose_name='Filename')),
            ],
            options={
                'verbose_name_plural': 'Files',
                'verbose_name': 'File',
            },
        ),
        migrations.AddField(
            model_name='backupfile',
            name='file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yadbu.File', verbose_name='File'),
        ),
    ]
