# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 17:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadbu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='backup',
            name='log',
            field=models.TextField(default='', verbose_name='Process log'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('partially', 'Partially'), ('error', 'Error')], max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='backupfile',
            name='file',
            field=models.TextField(verbose_name='File path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filename',
            field=models.TextField(help_text='Absolute path to file or mask, like `/path/to/file/my_backup.sql`, `/path/to/folder/*` or `/path/to/folder/*.jpeg`', verbose_name='Filename'),
        ),
    ]
