# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadbu', '0003_backup_yad_directory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backupfile',
            name='filename',
        ),
        migrations.AddField(
            model_name='backupfile',
            name='log',
            field=models.TextField(default='', verbose_name='Log'),
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('partially', 'Partially'), ('error', 'Error')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
