# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yadbu', '0004_auto_20170328_1716'),
    ]

    operations = [
        migrations.RenameField(
            model_name='backup',
            old_name='yad_directory',
            new_name='directory_name',
        ),
        migrations.AlterField(
            model_name='backup',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('success', 'Success'), ('error', 'Error'), ('aborted', 'Aborted')], default='new', max_length=20, verbose_name='Status'),
        ),
    ]
